version: '3.8'

services:
  db:
    networks:
      - dbapp
    container_name: claims-postgres
    image: postgres:14.5
    environment:
      POSTGRES_USER: claims
      POSTGRES_PASSWORD: claims
      POSTGRES_DB: claimsDB
    ports:
      - "5432:5432"

  redis:
    networks:
      - dbapp
    container_name: claims-redis
    image: redis:6.2.3
    ports:
      - "6380:6379"
    depends_on:
      - db

  web:
    networks:
      - dbapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1200:1200"
    command: uvicorn app.main:app --host 0.0.0.0 --port 1200 --access-log
    depends_on:
      - db
      - redis

networks:
  dbapp: {}